WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebApp/Models/Messagess.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class Messagess
    {
        public int Id { get; set; }
        public string messages { get; set; }
    }
}

WebApp/Models/Personel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class Personel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
    }
}

WebApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

WebApp/ViewComponents/Message/MessageViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
namespace WebApp.ViewComponents.Message
{
    public class MessageViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            List<Messagess> messages = new List<Messagess>
            {
                new Messagess { Id =1 , messages = "Salam"},
                new Messagess { Id =12 , messages = "Salam2"},
                new Messagess { Id =13 , messages = "Salam3"},
                new Messagess { Id =14 , messages = "Salam4"},
            };
           return View("Messages", messages);

        }
    }
}

WebApp/ViewComponents/MessageViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
namespace WebApp.ViewComponents
{
    public class MessageViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            List<Messagess> messages = new List<Messagess>
            {
                new Messagess { Id =1 , messages = "Salam"},
                new Messagess { Id =12 , messages = "Salam2"},
                new Messagess { Id =13 , messages = "Salam3"},
                new Messagess { Id =14 , messages = "Salam4"},
            };
            return View(viewName:"Default" , messages);

        }
    }
}

WebApp/ViewComponents/PersonellerViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.ViewComponents
{
    public class PersonellerViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Personel> datas = new List<Personel>{
        new Personel{ Id = 1 , Name = "Ad 1" , LastName = "Sagol1"},
        new Personel{ Id = 2 , Name = "Ad 2" , LastName = "Sagol2"},
        new Personel{ Id = 3 , Name = "Ad 3" , LastName = "Sagol3"},
        new Personel{ Id = 4 , Name = "Ad 4" , LastName = "Sagol4"},
        new Personel{ Id = 5 , Name = "Ad 5" , LastName = "Sagol5"},
    };

            var viewResult = View(viewName: "Default", model: datas);
            return await Task.FromResult<IViewComponentResult>(viewResult);
        }

    }
}

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp/Views/Shared/Components/Message/Default.cshtml
@model List<Messagess>
@foreach (var VARIABLE in Model)
{
    @VARIABLE.messages
}   

WebApp/Views/Shared/Components/Personeller/Default.cshtml
@model List<Personel>
<table class="table">
    <thead>
        <tr>
            <th class="col">Id</th>
            <th class="col">Ad</th>
            <th class="col">Soyad</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id </td>
                <td>@item.Name</td>
                <td>@item.LastName </td>
            </tr>
        }
    </tbody>
</table>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                               asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <section>
            <div class="row">
                <div class="col-md-12">
                    @await Component.InvokeAsync("Personeller")
                    <br>
                    @await Component.InvokeAsync("Message")
                </div>
            </div>
        </section>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>